### ISSUE TITLE
request: reduce output "by default login"

### ISSUE THREAD

**Issue by Adorfer** [viisauksena/gluon-banner#2]
if you manage hosts via very, very bad connection (at the edge of disconnect) it is really a bad idea to need to have 2kb+ data on the login screen. 
i wuld suggest to completly put most of the data to the info-command.

**Comment by viisauksena** [comment]
thanks for comment,
i thought about that . but decide against it 
main reason is - if there is such a connection i could easily pass any command "blind" there or i really should do smething against this bad connection. 
2500 byte of very very worthy data is ok - but yes - still there have to be a solution of unifying with info - or make them less doubling

**Comment by Adorfer** [comment]
if the buffers are full you can not enter something "blind". 
Even a Ctrl-C will not help clear the buffer.

**Comment by viisauksena** [comment]
i mean calling something like ... **ssh foo@bar 'echo anna und artur'** (be sure to use single quotes)
as i understand /etc/profile is only send/executed if i want a shell

**Comment by viisauksena** [comment]
i checked, you can do as i say if resources are rare - this also give you stdout so everything is fine and i close this here
